source "https://rubygems.org"

gem 'rhino', path: '../rhino'
gem 'rack'
gem 'bundler'

group :development do
  gem 'thin'
  gem 'rerun'
  gem 'test-unit', '~> 3.0'
  gem 'minitest', '~> 5.5'
  gem 'rack-test', '~> 0.6'
  gem 'pry'
end


